[package]
name = "message_utils"
version = "0.1.0"
authors = ["Michal Sloupensk√Ω <sloupensky@gmail.com>"]
edition = "2021"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["full"] }